#!/usr/bin/env -S PYTHONPATH=../../../../tools/extract-utils python3
#
# SPDX-FileCopyrightText: The LineageOS Project
# SPDX-License-Identifier: Apache-2.0
#

import os

from extract_utils.extract import extract_fns_user_type
from extract_utils.extract_star import extract_star_firmware
from extract_utils.fixups_blob import (
    blob_fixup,
    blob_fixups_user_type,
)
from extract_utils.fixups_lib import (
    lib_fixups,
    lib_fixups_user_type,
)
from extract_utils.main import (
    ExtractUtils,
    ExtractUtilsModule,
)

class TundraExtractUtilsModule(ExtractUtilsModule):
    def proprietary_file_path(self, file_name: str) -> str:
        return os.path.join(
            self.device_path,
            'proprietary-setup',
            file_name,
        )

namespace_imports = [
    'device/motorola/tundra',
    'hardware/motorola',
    'hardware/qcom-caf/sm8350',
    'hardware/qcom-caf/wlan',
    'vendor/qcom/opensource/commonsys-intf/display',
    'vendor/qcom/opensource/commonsys/display',
    'vendor/qcom/opensource/dataservices',
    'vendor/qcom/opensource/display',
]

def lib_fixup_vendor_suffix(lib: str, partition: str, *args, **kwargs):
    return f'{lib}_{partition}' if partition == 'vendor' else None

lib_fixups: lib_fixups_user_type = {
    **lib_fixups,
    (
        'com.qualcomm.qti.dpm.api@1.0',
        'libmmosal',
        'vendor.qti.imsrtpservice@3.0',
    ): lib_fixup_vendor_suffix,
}

blob_fixups: blob_fixups_user_type = {
    'vendor/lib64/libmot_chi_desktop_helper.so': blob_fixup()
        .add_needed('libgui_buffer_shim_vendor.so'),
    'vendor/lib64/sensors.moto.so': blob_fixup()
        .add_needed('libbase_shim.so'),
    'system_ext/etc/permissions/moto-telephony.xml': blob_fixup()
        .regex_replace('/system/', '/system_ext/'),
    'system_ext/priv-app/ims/ims.apk': blob_fixup()
        .apktool_patch('./proprietary-setup/ims-patches'),
    'vendor/etc/sensors/hals.conf': blob_fixup()
        .add_line_if_missing('sensors.moto_ext.so'),
    'vendor/lib64/libwvhidl.so': blob_fixup()
        .add_needed('libcrypto_shim.so'),
    'vendor/lib64/sensors.moto.so': blob_fixup()
        .add_needed('libbase_shim.so'),
    (
        'vendor/lib64/libdpps.so',
        'vendor/lib64/libsnapdragoncolor-manager.so',
    ): blob_fixup()
        .replace_needed('libtinyxml2.so', 'libtinyxml2-v34.so'),
}  # fmt: skip

extract_fns: extract_fns_user_type = {
    r'(bootloader|radio)\.img': extract_star_firmware,
}

module = TundraExtractUtilsModule(
    'tundra',
    'motorola',
    blob_fixups=blob_fixups,
    lib_fixups=lib_fixups,
    namespace_imports=namespace_imports,
    extract_fns=extract_fns,
    add_firmware_proprietary_file=True,
    add_generated_carriersettings=True,
)

# GitHub rejects pushes containing a file over 100MB. Some blobs (camera,
# modem firmware) exceed that, so split them into < 100MB parts after
# extraction and drop a vendorsetup.sh that reassembles them at build time
# (vendorsetup.sh files are auto-sourced by build/envsetup.sh).
GITHUB_MAX_FILE_SIZE = 100 * 1024 * 1024
SPLIT_CHUNK_SIZE = 90 * 1024 * 1024
SPLIT_SUFFIX = '.split.'

VENDORSETUP_SH_CONTENT = '''#!/bin/bash
# Auto-generated by extract-files.py.
# Reassembles proprietary files that were split to stay under GitHub's
# 100MB file size limit. Sourced automatically by build/envsetup.sh.

_tundra_reassemble_split_files() {
    local vendor_dir
    vendor_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    local part target
    while IFS= read -r part; do
        target="${part%.split.001}"
        if [ ! -f "$target" ] || [ "$part" -nt "$target" ]; then
            echo "tundra vendorsetup: reassembling $(basename "$target")"
            cat "$target".split.* > "$target"
        fi
    done < <(find "$vendor_dir" -name '*.split.001' 2>/dev/null)
}
_tundra_reassemble_split_files
'''


def get_vendor_path() -> str:
    script_dir = os.path.dirname(os.path.abspath(__file__))
    device_path = os.path.dirname(script_dir)
    root_path = os.path.normpath(os.path.join(device_path, '..', '..', '..'))
    return os.path.join(root_path, 'vendor', 'motorola', 'tundra')


def split_large_files(vendor_path: str):
    for root, _, file_names in os.walk(vendor_path):
        for file_name in file_names:
            if SPLIT_SUFFIX in file_name:
                continue

            file_path = os.path.join(root, file_name)
            if os.path.getsize(file_path) <= GITHUB_MAX_FILE_SIZE:
                continue

            print(f'Splitting {file_path} (exceeds GitHub 100MB limit)')
            with open(file_path, 'rb') as src:
                part_num = 1
                while chunk := src.read(SPLIT_CHUNK_SIZE):
                    part_path = f'{file_path}{SPLIT_SUFFIX}{part_num:03d}'
                    with open(part_path, 'wb') as dst:
                        dst.write(chunk)
                    part_num += 1

            os.remove(file_path)


def write_vendorsetup_sh(vendor_path: str):
    vendorsetup_path = os.path.join(vendor_path, 'vendorsetup.sh')
    with open(vendorsetup_path, 'w') as f:
        f.write(VENDORSETUP_SH_CONTENT)
    os.chmod(vendorsetup_path, 0o755)


if __name__ == '__main__':
    utils = ExtractUtils.device(module)
    utils.run()

    vendor_path = get_vendor_path()
    if os.path.isdir(vendor_path):
        split_large_files(vendor_path)
        write_vendorsetup_sh(vendor_path)
    else:
        print(f'Skipping file split: {vendor_path} not found')
